### ISSUE TITLE
Bad verification code?

### ISSUE THREAD

**Issue by GLodi** [geniushkg/github-oauth#8]
I cannot authorize users through the web flow because the API returns this json:

response is:{"error":"bad_verification_code","error_description":"The code passed is incorrect or expired.","error_uri":"https://developer.github.com/v3/oauth/#bad-verification-code"}

I called the library like this (in Kotlin):

val githubOauth: GithubOauth = GithubOauth.Builder()
            githubOauth.scopeList = arrayListOf("repo", "gist", "user")
            githubOauth
                    .withClientId("...")
                    .withClientSecret("...")
                    .withContext(this)
                    .packageName("giuliolodi.gitnav")
                    .nextActivity("giuliolodi.gitnav.EventActivity")
                    .debug(true)
                    .execute()

The intent to OauthActivity seems correct, but after logging through the webview, the bottom Authorize User button isn't clickable and the spinner is spinning indefinitely.

Is it parsing the URL incorrectly?

**Comment by geniushkg** [comment]
Sorry was busy, will check and revert back soon

**Comment by geniushkg** [comment]
It's not library because itself is just aided in webview interceptions of data passed URL, I doubt there is any chance of wrong URL parsing, 
It seems there is some problem with the setup of GitHub app, for the login page is loading, just recheck your GitHub app setup, I hope this will resolve the issue.

I am closing this issue as the library is not the culprit but still if you could not get things in correct way, I would gladly help you to get things in place.

Regards.
